#include "basic.typ"
#include "line-numbering.typ"
#include "numbering-separator.typ"
#include "line-slicing.typ"
#include "line-highlighting.typ"
#include "comments.typ"
#include "headers-and-footers.typ"
#include "language-tab.typ"
#include "indentation-lines.typ"
#include "hanging-indentation.typ"
#include "themes.typ"
#include "multi-numbering.typ"

// should be included last
#include "fast-preview.typ"
